### ISSUE TITLE
How to cancel search and show the whole password list again?

### ISSUE THREAD

**Issue by Boscop** [iamkarlson/keepass-quicksearch#10]
When I press Esc in the quicksearch bar to show the whole list again, it locks me out of Keepass so I have to re-enter my master pw. When I "select all" in the quicksearch bar and delete it, it doesn't show the whole list again. So how can I exit quicksearch and show the whole list again?

**Comment by iamkarlson** [comment]
I can hook these Esc calls but  I'm not sure that this right behaviour. Let's keep it as is.

**Comment by Boscop** [comment]
So how can I get out of the quicksearch and show the whole unfiltered list of entries again? :)

**Comment by iamkarlson** [comment]
just erase your input

**Comment by Boscop** [comment]
It doesn't work, I select all and then Del, it clears the quicksearch field but the old filter is *still* applied to the list :(
It only works by pressing backspace many times (once for each letter) but it doesn't work for the last letter! After deleting all letters, the list is still filtered as if the quicksearch string contained the former first letter!
