### ISSUE TITLE
Search by Tag

### ISSUE THREAD

**Issue by genaDeus** [iamkarlson/keepass-quicksearch#12]
Hi, iamkarlson!

Is there any possibility to add search by Tags? 

Thanks for the great plugin!

**Comment by gusowski1** [comment]
@iamkarlson any news on the feature request?

**Comment by iamkarlson** [comment]
@gusowski1 nope, I don't have time to spend on this project for a while and actually considering closing it as it is. I migrated to KeePassXC and works perfectly well for years already
