### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by mfinky** [iamkarlson/keepass-quicksearch#16]
Hello.

(1) Keepass out of the box has a very useful keyboard hshortcut to position the cursor into the search box, without using mouse.
If you hover over the dwn arrow that expands the original search box, yo usee this hint:
"Type to search the database (Ctrl+E)"
After deploying this plugin the (Ctrl+E) shortcut stopped working.

(2) Note (Ctrl+Shift+F) opens the "Find in selected group" dialog.  

Thank you,
Marcelo Finkielsztein

**Comment by iamkarlson** [comment]
Hi, 
I personally switched to keepassxc and have no time to support this plugin. Thanks
