### ISSUE TITLE
Default Search Box Still Visible

### ISSUE THREAD

**Issue by alexbde** [iamkarlson/keepass-quicksearch#9]
After installing latest version QuickSearch 2.27 default search box of latest KeePass 2.37 is still visible:

![temp](https://user-images.githubusercontent.com/17784818/34096290-1760bfa8-e3d5-11e7-92a2-83070308c8ab.png)

Do I have to hide it manually?

**Comment by iamkarlson** [comment]
yes, you do

**Comment by alexbde** [comment]
I took a closer look and found option ;) Thank you!
